require 'open3'

stdout, stderr, status = Open3.capture3("ausyscall x86_64 --dump")

File.open('syscall_table.c', "w") do |f|
  f.puts("/* This file is generated by generate_syscall_table.rb */")
  f.puts("/* Do not edit this file */")
  f.puts("const char *syscall_table[] = {")

  # ignore first line
  stdout.split("\n")[1..-1].each do |line|
    number, name = line.split(/\s+/)
    f.puts("  \"#{name}\",  // #{number}")
  end
  f.puts("};")
end

File.open('syscall_table.h', "w") do |f|
  f.puts("extern const char *syscall_table[];")
end

